name: Terraform Mesh Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Conecta GitHub à AWS via OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::458144597632:role/role-github
          aws-region: us-east-1

      # 3️⃣ Instala o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4️⃣ BUILD — inicializa Terraform
      - name: Terraform Init
        run: terraform init

      # 5️⃣ TEST — valida sintaxe
      - name: Terraform Validate
        run: terraform validate

      # 6️⃣ TEST — simula mudanças
      - name: Terraform Plan
        run: terraform plan

      # 7️⃣ DEPLOY — aplica na AWS
      - name: Terraform Apply
        run: terraform apply -auto-approve
